### PR TITLE
Compatibility react 0.29.0

### PR DESCRIPTION
**Pull request by jr-k**
Compatibility react 0.29.0

### CODE REVIEW

**Comment by kelset** [comment]
I'm sorry, why this PR is not being merged @zubricky?

It works, I just "installed" it into a RN 0.38 app and it works, but since it is not merged nor updated as npm package the only way to attach it has been overriding the content of the folder after `npm install`.

PS: @jr-k can you modify just a small thing in the README? Where you say 

> Update MainActivity.java in your project

You should say that in the MainActivity you add the import line, then in the MainApplication.java you add the import and the package parts.

Still, thanks for the good work both of you guys!

**Comment by santhosh77h** [comment]
@jr-k can you please merge I need this one to be working too badly and since I'm a guy from js not aware java stuff can you please do it.
thank you @kelset

**Comment by santhosh77h** [comment]
@kelset can you write a gist or something so that it would be understandable to the user to convert old projects to compatible with new version of react-native who comes from js like me who don;t have that knowledge of android or java.
Once again Thank you

**Comment by devbriguy** [comment]
Any status update to merge this? Thanks.

**Pull request merged**
